# Generated by Django 6.0.3 on 2026-03-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Precio', models.FloatField()),
                ('Cantidad', models.IntegerField()),
                ('Descripcion', models.TextField(max_length=50)),
                ('Categoria', models.TextField(max_length=20)),
                ('Fecha', models.DateField()),
            ],
        ),
    ]
